
This Databricks notebook, titled **understanding_quick_comm**, is designed to perform a comprehensive end-to-end data engineering and analytics workflow on an e-commerce dataset (Olist).

The notebook is organized into several key phases:

- **Data Ingestion & Integration:** It loads multiple CSV files (orders, items, payments, reviews, etc.) using pandas and merges them into a single Master Dataset (df) for unified analysis.
- **Data Transformation:** It handles schema cleaning, such as converting timestamp strings into datetime objects and translating product category names from Portuguese to English.
- **Feature Engineering:** It calculates business-specific metrics, such as delivery_delay_days, and categorizes orders as "Delayed" or "On Time."
- **Data Persistence:** It converts the processed Pandas DataFrame into a Spark DataFrame to save it as a permanent Delta table (final_quick_comm_dataset) in the Databricks workspace catalog.
- **Business Intelligence:** The final sections generate high-level Executive KPIs (GMV, AOV, Repeat Purchase Rate) and analyze the correlation between delivery performance and customer satisfaction scores.

# Load the Files First in DataFrames

In [0]:
import pandas as pd
import numpy as np

# Load datasets
orders = pd.read_csv("quick_comm_tables/olist_orders_dataset.csv")
items = pd.read_csv("quick_comm_tables/olist_order_items_dataset.csv")
payments = pd.read_csv("quick_comm_tables/olist_order_payments_dataset.csv")
reviews = pd.read_csv("quick_comm_tables/olist_order_reviews_dataset.csv")
products = pd.read_csv("quick_comm_tables/olist_products_dataset.csv")
customers = pd.read_csv("quick_comm_tables/olist_customers_dataset.csv")
category = pd.read_csv("quick_comm_tables/product_category_name_translation.csv")

## Translate Product Categories

In [0]:
products = products.merge(
    category,
    on="product_category_name",
    how="left"
)

## Build MASTER DATASET

In [0]:
df = orders.merge(items, on="order_id", how="left") \
           .merge(payments, on="order_id", how="left") \
           .merge(reviews, on="order_id", how="left") \
           .merge(products, on="product_id", how="left") \
           .merge(customers, on="customer_id", how="left")

In [0]:
date_cols = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date",
    "shipping_limit_date",
    "review_creation_date",
    "review_answer_timestamp"
]

for col in date_cols:
    df[col] = pd.to_datetime(df[col])

In [0]:
%sql
SELECT * FROM workspace.default.final_quick_comm_dataset LIMIT 100

order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,delivery_delay_days,delivery_status
17ae98e755b32ae8ec73470952de4de2,80d88401a15807dd28990dd932495bc6,delivered,2017-11-16T23:07:13.000Z,2017-11-16T23:16:41.000Z,2017-11-23T22:13:39.000Z,2017-12-06T18:44:26.000Z,2017-12-07T00:00:00.000Z,1.0,74fd207bb446a56583153f85de68b73c,54965bbe3e4f07ae045b90b0b8541f52,2017-11-22T23:16:41.000Z,120.0,21.33,2.0,voucher,1.0,75.0,d83ab20963957eab4af21ea4f71f16e0,5.0,null,null,2017-12-09T00:00:00.000Z,2017-12-12T02:33:05.000Z,cama_mesa_banho,41.0,729.0,1.0,1950.0,20.0,30.0,30.0,bed_bath_table,0fef599ec418d6a774d937017ee7ec2c,8820,mogi das cruzes,SP,-1.0,On Time
17ae98e755b32ae8ec73470952de4de2,80d88401a15807dd28990dd932495bc6,delivered,2017-11-16T23:07:13.000Z,2017-11-16T23:16:41.000Z,2017-11-23T22:13:39.000Z,2017-12-06T18:44:26.000Z,2017-12-07T00:00:00.000Z,1.0,74fd207bb446a56583153f85de68b73c,54965bbe3e4f07ae045b90b0b8541f52,2017-11-22T23:16:41.000Z,120.0,21.33,1.0,credit_card,2.0,66.33,d83ab20963957eab4af21ea4f71f16e0,5.0,null,null,2017-12-09T00:00:00.000Z,2017-12-12T02:33:05.000Z,cama_mesa_banho,41.0,729.0,1.0,1950.0,20.0,30.0,30.0,bed_bath_table,0fef599ec418d6a774d937017ee7ec2c,8820,mogi das cruzes,SP,-1.0,On Time
9a06f6b071c10b11ce8e6e8646dae224,89610c63a51a5b2ee28d3b69c6bfff3c,delivered,2018-06-09T09:22:08.000Z,2018-06-09T09:37:14.000Z,2018-06-11T14:02:00.000Z,2018-06-19T20:28:27.000Z,2018-07-16T00:00:00.000Z,1.0,d325b4b600e06bd11a1f8afdfdf3679c,06a2c3af7b3aee5d69171b0e14f0ee87,2018-06-19T09:32:12.000Z,154.99,30.11,1.0,credit_card,7.0,185.1,e9e81e73f44a0fc9212369c351f9d08b,4.0,otimo,bom,2018-06-20T00:00:00.000Z,2018-06-21T19:04:47.000Z,beleza_saude,46.0,1290.0,1.0,950.0,25.0,12.0,19.0,health_beauty,921c8a95cd7f1ba09d26223716253455,13070,campinas,SP,-27.0,On Time
d0028facea13f508e880202d7097a5a1,d2509c13692836fc0449e88cf9eb4858,delivered,2018-04-20T12:57:23.000Z,2018-04-25T03:51:13.000Z,2018-04-25T15:25:00.000Z,2018-04-27T12:08:59.000Z,2018-05-09T00:00:00.000Z,1.0,8cefe1c6f2304e7e6825150218ffc58c,ea8482cd71df3c1969d7b9473ff13abc,2018-05-02T03:51:13.000Z,27.99,7.39,1.0,boleto,1.0,35.38,ffc1a4080d67b1d3d06749f4f2d3ee59,4.0,null,null,2018-04-28T00:00:00.000Z,2018-05-01T20:41:51.000Z,telefonia,59.0,818.0,6.0,300.0,17.0,4.0,12.0,telephony,00050ab1314c0e55a6ca13cf7181fecf,13084,campinas,SP,-12.0,On Time
812114e24682287b1f3eb86f112707de,de94552cb07b7cbb5219d1616580a65c,delivered,2017-12-04T21:36:35.000Z,2017-12-05T09:30:45.000Z,2017-12-07T15:19:17.000Z,2017-12-19T15:53:56.000Z,2017-12-28T00:00:00.000Z,1.0,06bf70b6e1d67d96308235ef350edc61,2c9e548be18521d1c43cde1c582c6de8,2017-12-11T08:30:50.000Z,79.9,15.32,1.0,boleto,1.0,95.22,7a3fc44fbc09b8f38a5bead35c987785,4.0,null,null,2017-12-20T00:00:00.000Z,2017-12-20T23:27:27.000Z,brinquedos,48.0,284.0,2.0,950.0,105.0,10.0,11.0,toys,3526e8083b82706f0a66e58c84044cab,32676,betim,MG,-9.0,On Time
bc6c1d04178771a3ac9547f4770ab5f0,8fd50d32ac51d30d03b416bf7b27e72d,delivered,2017-10-27T10:27:03.000Z,2017-10-27T10:35:22.000Z,2017-10-31T21:53:55.000Z,2017-11-09T21:41:44.000Z,2017-11-17T00:00:00.000Z,1.0,422879e10f46682990de24d770e7f83d,1f50f920176fa81dab994f9023523100,2017-11-03T10:35:22.000Z,59.9,17.67,1.0,credit_card,4.0,77.57,c123f6ddcc806bd9bed231d6163f267e,5.0,null,null,2017-11-10T00:00:00.000Z,2017-11-13T10:01:10.000Z,ferramentas_jardim,56.0,348.0,2.0,1550.0,30.0,22.0,30.0,garden_tools,8cf98fbd02b0efdde35bbc7aab39764a,22271,rio de janeiro,RJ,-8.0,On Time
13d341318c77969f10d77e1382957542,3b6cfa5c62f4bfb3c09652d9ac539a8d,canceled,2018-08-01T09:43:22.000Z,2018-08-02T05:30:46.000Z,null,null,2018-08-08T00:00:00.000Z,1.0,336b5407e252cac6f4e4270979cec8ad,2e1a7d075abe038c1b2743005fe42ff1,2018-08-08T05:10:09.000Z,29.9,8.96,1.0,boleto,1.0,38.86,ca59740f42b644cb5d6aadcad4e54a81,1.0,Produto não recebido,null,2018-08-11T00:00:00.000Z,2018-08-11T03:11:43.000Z,beleza_saude,53.0,585.0,1.0,900.0,16.0,25.0,15.0,health_beauty,405f6a0f60d44b5ad32044970938191f,1224,sao paulo,SP,null,On Time
6bc8d0921edbcb67c01832572c2ca25d,6943ece6e8fee2637f6b06f466412be8,delivered,2017-05-06T10:29:30.000Z,2017-05-07T10:35:11.000Z,2017-05-09T07:57:52.000Z,2017-05-16T18:11:57.000Z,2017-06-02T00:00:00.000Z,1.0,3e67af30c5e3eae465fbf496aa88fc8b,a3a38f4affed601eb87a97788c949667,2017-05-11T10:35:11.000Z,89.9,17.19,1.0,credit_card,5.0,107.09,aeca86a7adbd314705f2cfde2f3a40a9,5.0,null,null,2017-05-17T00:00:00.000Z,2017-05-18T11:52:29.000Z,esporte_lazer,46.0,1352.0,3.0,450.0,28.0,13.0,24.0,sports_leisure,c4fe9fc8b5e1b4f9992db983d0429854,25815,tres rios,RJ,-17.0,On Time
91d95fd4dd24e83041031228370438b9,4c5a1e184ff4fd41b2d4ac212b95d0fc,delivered,2018-08-03T08:16:49.000Z,2018-08-04T04:24:17.000Z,2018-08-07T16:23:00.000Z,2018-08-14T20:48:38.000Z,2018-08-31T00:00:00.000Z,1.0,51f69f174d94a288c7c6d03095ccea9b,562fc2f2c2863ab7e79a9e4388a58a14,2018-08-07T04:24:17.000Z,29.99,22.93,1.0,boleto,1.0,52.92,45e290c98f407e6c90a75d81fc14d005,5.0,Segunda compra que faço!,"A capa aderiu bem no meu Redmi 4x, recomendo!",2018-08-15T00:00:00.000Z,2018-08-16T09:33:57.000Z,telefonia,57.0,364.0,1.0,150.0,22.0,7.0,14.0,telephony,cfa69922f9968e0e6271647abda09b09,64063,teresina,PI,-17.0,On Time
c04ccf5367e419a74f5589f156a0b8e1,6f7d7ececcfee77e1c4d624c81a37aa2,delivered,2017-09-30T19:45:40.000Z,2017-09-30T20:14:23.000Z,2017-10-03T17:06:05.000Z,2017-10-10T17:32:52.000Z,2017-10-30T00:00:00.000Z,1.0,6a1a04054158fe995e1688d8f79605b2,9616352088dcf83a7c06637f4ebf1c80,2017-10-09T20:14:23.000Z,59.9,13.44,1.0,credit_card,1.0,73.34,644537a36bc46b09f52e494d2922819a,5.0,null,null,2017-10-11T00:00:00.000Z,2017-10-11T22:24:22.000Z,esporte_lazer,59.0,254.0,1.0,1650.0,40.0,45.0,25.0,sports_leisure,2362ea945dafafd2f3c196effdbdb83e,11453,guaruja,SP,-20.0,On Time
cd38154bf340cc6b376898bd4b82b125,6c0f0dd8985cc0a789fb68327a00bc39,delivered,2018-05-07T15:06:12.000Z,2018-05-07T16:55:52.000Z,2018-05-09T15:48:00.000Z,2018-05-18T18:08:38.000Z,2018-05-28T00:00:00.000Z,1.0,53b36df67ebb7c41585e8d54d6772e08,7d13fca15225358621be4086e1eb0964,2018-05-11T16:55:52.000Z,99.9,0.0,1.0,credit_card,4.0,99.9,1576c7acebbaa1cf62b399bc62130148,5.0,null,null,2018-05-19T00:00:00.000Z,2018-05-21T03:18:06.000Z,relogios_presentes,33.0,523.0,3.0,584.0,16.0,11.0,13.0,watches_gifts,7c8cdb09963770391622f23f120085f7,24436,sao goncalo,RJ,-10.0,On Time
bbf778080cc883a8de2e500c0e490c75,437c6e906ba1e09eacb6d28d1de3f061,delivered,2018-04-01T21:03:55.000Z,2018-04-01T21:15:10.000Z,2018-04-02T19:33:05.000Z,2018-04-10T22:58:42.000Z,2018-05-08T00:00:00.000Z,1.0,873d2aa3911060e77ac89009410aa908,6c177e38df6d3f34182b1f1d427231bf,2018-04-10T21:15:10.000Z,148.0,22.75,1.0,credit_card,2.0,170.75,decd1f3ad4afa22a0544c99eb839a305,3.0,null,null,2018-04-11T00:00:00.000Z,2018-04-13T00:44:18.000Z,telefonia,54.0,172.0,2.0,150.0,20.0,5.0,12.0,telephony,09e9dc48aef9cb76de884bbbb8adf731,28895,rio das ostras,RJ,-28.0,On Time
bf79e4fa55a389d494f47feb2654892c,e8759aed1027f77226dddeb7c7481f11,delivered,2017-01-31T21:11:10.000Z,2017-02-01T09:45:26.000Z,2017-02-01T14:29:06.000Z,2017-03-13T12:09:45.000Z,2017-02-27T00:00:00.000Z,1.0,fe09eb5f7bfcb79d05df7c4e83ec204e,2a1348e9addc1af5aaa619b1a3679d6b,2017-02-04T21:11:10.000Z,14.9,14.52,1.0,boleto,1.0,29.42,6b63898cfd07a3793858c7591753983e,1.0,null,null,2017-03-01T00:00:00.000Z,2017-03-01T03:18:30.000Z,consoles_games,60.0,574.0,1.0,200.0,16.0,2.0,11.0,consoles_games,62972384465273ec1b0d3cf772abc390,29170,serra,ES,14.0,Delayed
fb7aedc5796ee214a87461ece45355e7,40d3460ad3b63de04990975d2fb3330c,delivered,2018-02-15T21:39:10.000Z,2018-02-16T07:50:27.000Z,2018-02-19T14:08:52.000Z,2018-03-05T19:59:37.000Z,2018-03-09T00:00:00.000Z,1.0,0f56d67a1f266a9cf5af6ffd7895bed6,5cf13accae3222c70a9cac40818ae839,2018-02-22T06:50:27.000Z,94.9,16.42,1.0,boleto,1.0,111.32,3fcb53d0f956c80ac7712fad7dc52529,5.0,null,null,2018-03-06T00:00:00.000Z,2018-03-07T12:08:07.000Z,pet_shop,53.0,1024.0,2.0,600.0,21.0,18.0,20.0,pet_shop,2872114274bbdff3c561c28366c1979b,4475,sao paulo,SP,-4.0,On Time
c6c304f8417f11d277f34b8a6ffe1532,3be9371fc3606f9f4572254708def45a,delivered,2018-04-30T09:10:16.000Z,2018-04-30T09:35:45.000Z,2018-05-03T06:31:00.000Z,2018-05-11T16:42:34.000Z,2018-05-25T00:00:00.000Z,1.0,2948658cb6abc82847412be7201bfc4c,955fee9216a65b617aa5c0531780ce60,2018-05-07T09:30:26.000Z,110.0,34.76,1.0,credit_card,3.0,144.76,d17f993c9535eb6fcef6095f4788aa16,3.0,null,null,2018-05-12T00:00:00.000Z,2018-05-13T00:40:17.000Z,beleza_saude,59.0,1030.0,5.0,3500.0,36.0,25.0,21.0,health_beauty,593e30b76f4138d5a9f0736ccedb9a40,58030,joao pessoa,PB,-14.0,On Time
90a35d9f1707a645c3bd2dda9c3f2643,5d94eb3a651e44419266ec8fddbd57be,delivered,2017-12-02T16:44:06.000Z,2017-12-02T16:59:01.000Z,2017-12-04T18:04:30.000Z,2017-12-19T16:44:45.000Z,2018-01-02T00:00:00.000Z,1.0,d2085f7e0f9533605386960fc7e987ec,aac29b1b99776be73c3049939652091d,2017-12-08T16:59:01.000Z,12.49,15.1,1.0,credit_card,1.0,110.36,null,null,null,null,null,null,ferramentas_jardim,40.0,207.0,4.0,150.0,16.0,2.0,11.0,garden_tools,a611c80155435e6a86012d159d9e5007,71741,brasilia,DF,-14.0,On Time
90a35d9f1707a645c3bd2dda9c3f2643,5d94eb3a651e44419266ec8fddbd57be,delivered,2017-12-02T16:44:06.000Z,2017-12-02T16:59:01.000Z,2017-12-04T18:04:30.000Z,2017-12-19T16:44:45.000Z,2018-01-02T00:00:00.000Z,2.0,d2085f7e0f9533605386960fc7e987ec,aac29b1b99776be73c3049939652091d,2017-12-08T16:59:01.000Z,12.49,15.1,1.0,credit_card,1.0,110.36,null,null,null,null,null,null,ferramentas_jardim,40.0,207.0,4.0,150.0,16.0,2.0,11.0,garden_tools,a611c80155435e6a86012d159d9e5007,71741,brasilia,DF,-14.0,On Time
90a35d9f1707a645c3bd2dda9c3f2643,5d94eb3a651e44419266ec8fddbd57be,delivered,2017-12-02T16:44:06.000Z,2017-12-02T16:59:01.000Z,2017-12-04T18:04:30.000Z,2017-12-19T16:44:45.000Z,2018-01-02T00:00:00.000Z,3.0,d2085f7e0f9533605386960fc7e987ec,aac29b1b99776be73c3049939652091d,2017-12-08T16:59:01.000Z,12.49,15.1,1.0,credit_card,1.0,110.36,null,null,null,null,null,null,ferramentas_jardim,40.0,207.0,4.0,150.0,16.0,2.0,11.0,garden_tools,a611c80155435e6a86012d159d9e5007,71741,brasilia,DF,-14.0,On Time
90a35d9f1707a645c3bd2dda9c3f2643,5d94eb3a651e44419266ec8fddbd57be,delivered,2017-12-02T16:44:06.000Z,2017-12-02T16:59:01.000Z,2017-12-04T18:04:30.000Z,2017-12-19T16:44:45.000Z,2018-01-02T00:00:00.000Z,4.0,d2085f7e0f9533605386960fc7e987ec,aac29b1b99776be73c3049939652091d,2017-12-08T16:59:01.000Z,12.49,15.1,1.0,credit_card,1.0,110.36,null,null,null,null,null,null,ferramentas_jardim,40.0,207.0,4.0,150.0,16.0,2.0,11.0,garden_tools,a611c80155435e6a86012d159d9e5007,71741,brasilia,DF,-14.0,On Time
fbfba2ffdcf0d5f4e4eeebc83a18b0d3,7decbed5e9dba1c414ec29e6642fc782,delivered,2018-03-18T16:14:17.000Z,2018-03-18T16:30:26.000Z,2018-03-20T15:09:35.000Z,2018-03-23T21:07:04.000Z,2018-04-10T00:00:00.000Z,1.0,7814c273ab16783d73a9863ebfa8b141,1025f0e2d44d7041d6cf58b6550e0bfa,2018-03-27T16:30:26.000Z,250.0,37.77,1.0,credit_card,4.0,287.77,dc3ae541bd971d5d47b552d5892c1c55,5.0,null,Otimo...,2018-03-24T00:00:00.000Z,2018-03-25T01:03:08.000Z,moveis_decoracao,51.0,756.0,1.0,12250.0,45.0,35.0,45.0,furniture_decor,6dfd32ebdda748f99584cb407510bb89,14500,ituverava,SP,-18.0,On Time
3b762d0fc1d3436171716bc6c3ae8497,37566e2c7b3fc323c530b838b0178401,delivered,2018-03-07T16:36:33.000Z,2018-03-08T12:45:28.000Z,2018-03-08T23:10:37.000Z,2018-04-02T17:12:33.000Z,2018-04-04T00:00:00.000Z,1.0,e91bea61ea0d665e4c445d6461586e13,4e5725ba188db8252977a4f0227bd462,2018-03-14T12:45:28.000Z,360.0,20.4,1.0,credit_card,3.0,380.4,7fda2e9bb9cbc1e7b6444e299d221934,5.0,null,null,2018-04-03T00:00:00.000Z,2018-04-03T19:12:07.000Z,informatica_acessorios,60.0,540.0,1.0,3400.0,21.0,17.0,15.0,computers_accessories,452185d4297d39dc139799ce818d8307,97065,santa maria,RS,-2.0,On Time
fc8b5696b23d0710ae737ff9c16f80ea,8953cac02ef5531e3b49afc55cc21232,delivered,2018-01-15T21:54:38.000Z,2018-01-15T22:10:41.000Z,2018-01-16T22:25:09.000Z,2018-01-27T12:09:29.000Z,2018-02-14T00:00:00.000Z,1.0,5389dbdf62ed8bee6b52fab9c9891f2e,897060da8b9a21f655304d50fd935913,2018-01-23T22:10:41.000Z,83.23,15.33,1.0,credit_card,1.0,98.56,70e766e69c12f5e68cacfcd5a367a6e6,3.0,null,bom produto.,2018-01-28T00:00:00.000Z,2018-01-29T21:14:37.000Z,informatica_acessorios,54.0,1416.0,3.0,200.0,16.0,14.0,13.0,computers_accessories,6b016ce767bbafe912ab0b8dce8e245b,88095,florianopolis,SC,-18.0,On Time
6debbd8568d730f4959d1fac74ed0315,66f7666afc694d88befe0d5e48871138,delivered,2018-01-12T19:23:58.000Z,2018-01-12T19:31:26.000Z,2018-01-23T00:08:27.000Z,2018-02-27T00:35:57.000Z,2018-02-14T00:00:00.000Z,1.0,5e211f15646acded537a9d1646f6a268,9c068d10aca38e85c50202e17b4a7e88,2018-01-18T19:31:26.000Z,194.9,39.26,1.0,credit_card,4.0,234.16,null,null,null,null,null,null,automotivo,59.0,759.0,2.0,2250.0,16.0,15.0,16.0,auto,b36e99aa28fa8a66d98742c741d653e9,40283,salvador,BA,13.0,Delayed
47cf7e28d8f434cd6a3f4825953cdbac,8fceafecb6f78c92c97dde2f6d1cac63,delivered,2018-05-03T20:57:34.000Z,2018-05-03T21:11:30.000Z,2018-05-04T10:42:00.000Z,2018-05-11T20:47:31.000Z,2018-05-17T00:00:00.000Z,1.0,b2f15c23f560da3b247e1090d9d12be7,2ff97219cb8622eaf3cd89b7d9c09824,2018-05-09T21:11:30.000Z,16.9,7.71,1.0,credit_card,1.0,49.22,fe1aad5c0dd87fd4e66e008a98b77ad2,5.0,Gostei.,Foi entrgue bem antes do prazo.,2018-05-12T00:00:00.000Z,2018-05-13T08:50:01.000Z,utilidades_domesticas,60.0,608.0,4.0,200.0,16.0,6.0,12.0,housewares,39c13cde8e30f2f4516cdcd3c3100ddf,11725,praia grande,SP,-6.0,On Time
47cf7e28d8f434cd6a3f4825953cdbac,8fceafecb6f78c92c97dde2f6d1cac63,delivered,2018-05-03T20:57:34.000Z,2018-05-03T21:11:30.000Z,2018-05-04T10:42:00.000Z,2018-05-11T20:47:31.000Z,2018-05-17T00:00:00.000Z,2.0,b2f15c23f560da3b247e1090d9d12be7,2ff97219cb8622eaf3cd89b7d9c09824,2018-05-09T21:11:30.000Z,16.9,7.71,1.0,credit_card,1.0,49.22,fe1aad5c0dd87fd4e66e008a98b77ad2,5.0,Gostei.,Foi entrgue bem antes do prazo.,2018-05-12T00:00:00.000Z,2018-05-13T08:50:01.000Z,utilidades_domesticas,60.0,608.0,4.0,200.0,16.0,6.0,12.0,housewares,39c13cde8e30f2f4516cdcd3c3100ddf,11725,praia grande,SP,-6.0,On Time
642b39405abba96bc0e134680e8ceb02,bffd28b4af20bc7b1a477fe80e190c77,unavailable,2017-03-05T09:28:24.000Z,2017-03-07T04:10:29.000Z,null,null,2017-04-03T00:00:00.000Z,null,null,null,null,null,null,1.0,boleto,1.0,214.1,c5a4690da16a9a92b4e419dba2f69daa,1.0,null,Perderam um cliente,2017-04-06T00:00:00.000Z,2017-04-06T14:43:10.000Z,null,null,null,null,null,null,null,null,null,20763743ec53eec3a9949781bf459e6e,88390,barra velha,SC,null,On Time
9f7d6c40a518954cc676b40cf3e2c61a,cb4f601a5eebf94e41b2bfc80cbc8e62,delivered,2018-05-01T19:11:36.000Z,2018-05-01T19:33:39.000Z,2018-05-07T12:31:00.000Z,2018-05-11T23:06:29.000Z,2018-05-29T00:00:00.000Z,1.0,0a57f7d2c983bcf8188589a5fea4a8da,4869f7a5dfa277a7dca6462dcf3b52b2,2018-05-09T19:31:19.000Z,95.9,17.58,1.0,credit_card,5.0,113.48,d0f64e0ac622b5a34c2c40479fbb2714,5.0,null,null,2018-05-12T00:00:00.000Z,2018-05-14T04:37:04.000Z,relogios_presentes,33.0,932.0,1.0,396.0,18.0,11.0,14.0,watches_gifts,a36022b1b85179867ad8ddec7393824e,1313,sao paulo,SP,-18.0,On Time
f4b84983666d1ac021c0522f00a405c0,6a4d0a6c3f1bbcd88b4e58633a4f8184,delivered,2018-08-21T12:21:04.000Z,2018-08-21T12:30:47.000Z,2018-08-21T14:56:00.000Z,2018-08-24T19:41:45.000Z,2018-08-24T00:00:00.000Z,1.0,8acf0061d1c7b72c3a4857db994ecc79,17ca9b9e9b9ef8fdb529001b49ebb50f,2018-08-23T12:30:47.000Z,69.97,11.98,1.0,credit_card,2.0,81.95,22c417c4ea6e742c0208dfea13e089a3,1.0,bom,"O produto não é o que eu esperava, mas serve",2018-08-25T00:00:00.000Z,2018-08-28T10:58:22.000Z,cama_mesa_banho,54.0,1004.0,1.0,1150.0,16.0,30.0,40.0,bed_bath_table,0afbb1db4938251436ec902d3e3b4c91,32183,contagem,MG,0.0,On Time
12988705c14f4a1b899dcfba47f4fd49,0a42f79acdee1c80dc33cc9539e13b9a,delivered,2018-05-11T01:03:08.000Z,2018-05-12T01:16:37.000Z,2018-05-15T14:20:00.000Z,2018-05-22T20:27:36.000Z,2018-06-06T00:00:00.000Z,1.0,3ac29f1f25166dcc60b97e65d9a5885c,440dd6ab244315c632130ecfb63827b1,2018-05-17T01:16:37.000Z,144.0,43.59,1.0,credit_card,2.0,187.59,5916eb7c953c3b7d03b45f14802cb708,5.0,10,Muito obrigado,2018-05-23T00:00:00.000Z,2018-05-26T02:47:31.000Z,esporte_lazer,60.0,1493.0,2.0,1050.0,80.0,8.0,15.0,sports_leisure,fa9d48426871b8a665348bae305bbc2a,86975,mandaguari,PR,-15.0,On Time
ab960bedab25b686fc5202ccf9be3094,588a6c2298f57752c9458dd79c675f36,delivered,2018-05-08T13:12:21.000Z,2018-05-08T13:35:16.000Z,2018-05-08T15:41:00.000Z,2018-05-14T22:05:43.000Z,2018-06-04T00:00:00.000Z,1.0,93a12c289ca2b78e7069e469f5053ef2,88460e8ebdecbfecb5f9601833981930,2018-05-22T13:30:59.000Z,144.9,14.13,1.0,credit_card,1.0,159.03,c8d86e9469cc55281daf9bb4a3f17507,1.0,"Pus 1, mas é zero estrela",Venda de cartuchos falsificados/usados (mensagem da minha impressora HP quando tentei instalar os cartuchos). Providências somente sob pressão. Enorme perda de tempo com todo o processo.,2018-05-15T00:00:00.000Z,2018-06-12T13:10:24.000Z,informatica_acessorios,55.0,408.0,1.0,233.0,16.0,14.0,15.0,computers_accessories,b0bc6af493883ddf6e65a498f4f197d3,80035,curitiba,PR,-21.0,On Time
44c20b916ad4112aab925e7ecbd6b1fe,36ba612573e878b95e3e5de1b17ee495,delivered,2018-04-12T17:12:52.000Z,2018-04-12T17:29:31.000Z,2018-04-13T19:05:02.000Z,2018-04-14T17:42:13.000Z,2018-04-30T00:00:00.000Z,1.0,d25142f887810041ec819fbabafa8c76,f262cbc1c910c83959f849465454ddd3,2018-04-18T17:29:31.000Z,99.99,7.56,1.0,credit_card,1.0,107.55,f054f9604fad625d8eb73a972592f911,5.0,null,null,2018-04-15T00:00:00.000Z,2018-04-16T21:58:48.000Z,informatica_acessorios,43.0,382.0,1.0,350.0,21.0,9.0,17.0,computers_accessories,6923959f3749c4dadeee7ef220231bfc,7793,cajamar,SP,-16.0,On Time
84270b9b2f185170b4b29b448ef3a0cc,b1fb921da8da31f114b8f25530967fe7,delivered,2017-06-19T20:32:27.000Z,2017-06-20T11:05:29.000Z,2017-06-21T09:58:41.000Z,2017-06-28T15:32:55.000Z,2017-07-07T00:00:00.000Z,1.0,777d2e438a1b645f3aec9bd57e92672c,4a3ca9315b744ce9f8e9374361493884,2017-06-26T11:05:29.000Z,69.9,12.83,1.0,boleto,1.0,82.73,be049948791daaa7ada6a0756ae8e9a2,4.0,null,Bom,2017-06-29T00:00:00.000Z,2017-06-30T01:02:31.000Z,cama_mesa_banho,58.0,689.0,1.0,950.0,45.0,15.0,35.0,bed_bath_table,e67af1efd445becc5019902668fe3218,16901,andradina,SP,-9.0,On Time
dd3f89a5330b29871785935cab37fcbc,bb2b8b9b95fc43819ab3ba6c5b6e3fd2,delivered,2018-02-05T11:07:13.000Z,2018-02-05T11:35:35.000Z,2018-02-09T17:52:06.000Z,2018-02-15T23:37:01.000Z,2018-02-23T00:00:00.000Z,1.0,7855801875dac05bda454284be8be7db,f76a3b1349b6df1ee875d1f3fa4340f0,2018-02-13T11:35:35.000Z,139.9,13.53,1.0,credit_card,1.0,153.43,67e1883c325520b179e45f978ad5aab5,5.0,null,null,2018-02-16T00:00:00.000Z,2018-02-19T10:48:36.000Z,utilidades_domesticas,58.0,1854.0,1.0,3500.0,36.0,30.0,32.0,housewares,af70fa34dfd5b02c0a4d7250a4026230,3111,sao paulo,SP,-8.0,On Time
26fa952896224ad19bba5529c49d077b,fb0eae96da2e5b5cd5b9756f883714cc,delivered,2018-06-21T21:44:11.000Z,2018-06-23T01:00:15.000Z,2018-06-25T08:27:00.000Z,2018-07-02T20:07:35.000Z,2018-07-20T00:00:00.000Z,1.0,d56c3ea4f42e37bc279359ab8ca16479,31561f325664a8a7aba4c8d0c3a9b3db,2018-06-28T01:00:15.000Z,39.49,15.38,1.0,credit_card,3.0,54.87,d08f77294705fac3818d969df4545826,5.0,Ótimo produto,Realmente é uma meia de qualidade.,2018-07-03T00:00:00.000Z,2018-07-03T23:31:48.000Z,automotivo,60.0,651.0,1.0,100.0,16.0,3.0,11.0,auto,7d9f821a5a0c0f80321140886696e7aa,90550,porto alegre,RS,-18.0,On Time

In [0]:
df.describe()

            order_purchase_timestamp  ... customer_zip_code_prefix
count                         119143  ...            119143.000000
mean   2017-12-29 18:36:13.115760128  ...             35033.451298
min              2016-09-04 21:15:19  ...              1003.000000
25%              2017-09-10 20:15:46  ...             11250.000000
50%              2018-01-17 11:59:12  ...             24240.000000
75%              2018-05-03 13:18:30  ...             58475.000000
max              2018-10-17 17:30:18  ...             99990.000000
std                              NaN  ...             29823.198969

[8 rows x 23 columns]

In [0]:
df.isnull().sum()

order_id                              0
customer_id                           0
order_status                          0
order_purchase_timestamp              0
order_approved_at                   177
order_delivered_carrier_date       2086
order_delivered_customer_date      3421
order_estimated_delivery_date         0
order_item_id                       833
product_id                          833
seller_id                           833
shipping_limit_date                 833
price                               833
freight_value                       833
payment_sequential                    3
payment_type                          3
payment_installments                  3
payment_value                         3
review_id                           997
review_score                        997
review_comment_title             105154
review_comment_message            68898
review_creation_date                997
review_answer_timestamp             997
product_category_name              2542
product_name_lenght                2542
product_description_lenght         2542
product_photos_qty                 2542
product_weight_g                    853
product_length_cm                   853
product_height_cm                   853
product_width_cm                    853
product_category_name_english      2567
customer_unique_id                    0
customer_zip_code_prefix              0
customer_city                         0
customer_state                        0
dtype: int64

## Create BUSINESS METRICS

In [0]:
#delivery delay
df["delivery_delay_days"] = (
    df["order_delivered_customer_date"] -
    df["order_estimated_delivery_date"]
).dt.days
#delivery status
df["delivery_status"] = np.where(
    df["delivery_delay_days"] > 0,
    "Delayed",
    "On Time"
)

# CREATE dataset with the above df

In [0]:
%sql
SELECT current_catalog() as catalog, current_schema() as schema

catalog,schema
workspace,default

In [0]:
# Save as a permanent Delta table with explicit catalog and schema
spark_df = spark.createDataFrame(df)
spark_df.write.format("delta").mode("overwrite").saveAsTable("workspace.default.final_quick_comm_dataset")

In [0]:
%sql
SELECT * FROM workspace.default.final_quick_comm_dataset LIMIT 100

order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,delivery_delay_days,delivery_status
17ae98e755b32ae8ec73470952de4de2,80d88401a15807dd28990dd932495bc6,delivered,2017-11-16T23:07:13.000Z,2017-11-16T23:16:41.000Z,2017-11-23T22:13:39.000Z,2017-12-06T18:44:26.000Z,2017-12-07T00:00:00.000Z,1.0,74fd207bb446a56583153f85de68b73c,54965bbe3e4f07ae045b90b0b8541f52,2017-11-22T23:16:41.000Z,120.0,21.33,2.0,voucher,1.0,75.0,d83ab20963957eab4af21ea4f71f16e0,5.0,null,null,2017-12-09T00:00:00.000Z,2017-12-12T02:33:05.000Z,cama_mesa_banho,41.0,729.0,1.0,1950.0,20.0,30.0,30.0,bed_bath_table,0fef599ec418d6a774d937017ee7ec2c,8820,mogi das cruzes,SP,-1.0,On Time
17ae98e755b32ae8ec73470952de4de2,80d88401a15807dd28990dd932495bc6,delivered,2017-11-16T23:07:13.000Z,2017-11-16T23:16:41.000Z,2017-11-23T22:13:39.000Z,2017-12-06T18:44:26.000Z,2017-12-07T00:00:00.000Z,1.0,74fd207bb446a56583153f85de68b73c,54965bbe3e4f07ae045b90b0b8541f52,2017-11-22T23:16:41.000Z,120.0,21.33,1.0,credit_card,2.0,66.33,d83ab20963957eab4af21ea4f71f16e0,5.0,null,null,2017-12-09T00:00:00.000Z,2017-12-12T02:33:05.000Z,cama_mesa_banho,41.0,729.0,1.0,1950.0,20.0,30.0,30.0,bed_bath_table,0fef599ec418d6a774d937017ee7ec2c,8820,mogi das cruzes,SP,-1.0,On Time
9a06f6b071c10b11ce8e6e8646dae224,89610c63a51a5b2ee28d3b69c6bfff3c,delivered,2018-06-09T09:22:08.000Z,2018-06-09T09:37:14.000Z,2018-06-11T14:02:00.000Z,2018-06-19T20:28:27.000Z,2018-07-16T00:00:00.000Z,1.0,d325b4b600e06bd11a1f8afdfdf3679c,06a2c3af7b3aee5d69171b0e14f0ee87,2018-06-19T09:32:12.000Z,154.99,30.11,1.0,credit_card,7.0,185.1,e9e81e73f44a0fc9212369c351f9d08b,4.0,otimo,bom,2018-06-20T00:00:00.000Z,2018-06-21T19:04:47.000Z,beleza_saude,46.0,1290.0,1.0,950.0,25.0,12.0,19.0,health_beauty,921c8a95cd7f1ba09d26223716253455,13070,campinas,SP,-27.0,On Time
d0028facea13f508e880202d7097a5a1,d2509c13692836fc0449e88cf9eb4858,delivered,2018-04-20T12:57:23.000Z,2018-04-25T03:51:13.000Z,2018-04-25T15:25:00.000Z,2018-04-27T12:08:59.000Z,2018-05-09T00:00:00.000Z,1.0,8cefe1c6f2304e7e6825150218ffc58c,ea8482cd71df3c1969d7b9473ff13abc,2018-05-02T03:51:13.000Z,27.99,7.39,1.0,boleto,1.0,35.38,ffc1a4080d67b1d3d06749f4f2d3ee59,4.0,null,null,2018-04-28T00:00:00.000Z,2018-05-01T20:41:51.000Z,telefonia,59.0,818.0,6.0,300.0,17.0,4.0,12.0,telephony,00050ab1314c0e55a6ca13cf7181fecf,13084,campinas,SP,-12.0,On Time
812114e24682287b1f3eb86f112707de,de94552cb07b7cbb5219d1616580a65c,delivered,2017-12-04T21:36:35.000Z,2017-12-05T09:30:45.000Z,2017-12-07T15:19:17.000Z,2017-12-19T15:53:56.000Z,2017-12-28T00:00:00.000Z,1.0,06bf70b6e1d67d96308235ef350edc61,2c9e548be18521d1c43cde1c582c6de8,2017-12-11T08:30:50.000Z,79.9,15.32,1.0,boleto,1.0,95.22,7a3fc44fbc09b8f38a5bead35c987785,4.0,null,null,2017-12-20T00:00:00.000Z,2017-12-20T23:27:27.000Z,brinquedos,48.0,284.0,2.0,950.0,105.0,10.0,11.0,toys,3526e8083b82706f0a66e58c84044cab,32676,betim,MG,-9.0,On Time
bc6c1d04178771a3ac9547f4770ab5f0,8fd50d32ac51d30d03b416bf7b27e72d,delivered,2017-10-27T10:27:03.000Z,2017-10-27T10:35:22.000Z,2017-10-31T21:53:55.000Z,2017-11-09T21:41:44.000Z,2017-11-17T00:00:00.000Z,1.0,422879e10f46682990de24d770e7f83d,1f50f920176fa81dab994f9023523100,2017-11-03T10:35:22.000Z,59.9,17.67,1.0,credit_card,4.0,77.57,c123f6ddcc806bd9bed231d6163f267e,5.0,null,null,2017-11-10T00:00:00.000Z,2017-11-13T10:01:10.000Z,ferramentas_jardim,56.0,348.0,2.0,1550.0,30.0,22.0,30.0,garden_tools,8cf98fbd02b0efdde35bbc7aab39764a,22271,rio de janeiro,RJ,-8.0,On Time
13d341318c77969f10d77e1382957542,3b6cfa5c62f4bfb3c09652d9ac539a8d,canceled,2018-08-01T09:43:22.000Z,2018-08-02T05:30:46.000Z,null,null,2018-08-08T00:00:00.000Z,1.0,336b5407e252cac6f4e4270979cec8ad,2e1a7d075abe038c1b2743005fe42ff1,2018-08-08T05:10:09.000Z,29.9,8.96,1.0,boleto,1.0,38.86,ca59740f42b644cb5d6aadcad4e54a81,1.0,Produto não recebido,null,2018-08-11T00:00:00.000Z,2018-08-11T03:11:43.000Z,beleza_saude,53.0,585.0,1.0,900.0,16.0,25.0,15.0,health_beauty,405f6a0f60d44b5ad32044970938191f,1224,sao paulo,SP,null,On Time
6bc8d0921edbcb67c01832572c2ca25d,6943ece6e8fee2637f6b06f466412be8,delivered,2017-05-06T10:29:30.000Z,2017-05-07T10:35:11.000Z,2017-05-09T07:57:52.000Z,2017-05-16T18:11:57.000Z,2017-06-02T00:00:00.000Z,1.0,3e67af30c5e3eae465fbf496aa88fc8b,a3a38f4affed601eb87a97788c949667,2017-05-11T10:35:11.000Z,89.9,17.19,1.0,credit_card,5.0,107.09,aeca86a7adbd314705f2cfde2f3a40a9,5.0,null,null,2017-05-17T00:00:00.000Z,2017-05-18T11:52:29.000Z,esporte_lazer,46.0,1352.0,3.0,450.0,28.0,13.0,24.0,sports_leisure,c4fe9fc8b5e1b4f9992db983d0429854,25815,tres rios,RJ,-17.0,On Time
91d95fd4dd24e83041031228370438b9,4c5a1e184ff4fd41b2d4ac212b95d0fc,delivered,2018-08-03T08:16:49.000Z,2018-08-04T04:24:17.000Z,2018-08-07T16:23:00.000Z,2018-08-14T20:48:38.000Z,2018-08-31T00:00:00.000Z,1.0,51f69f174d94a288c7c6d03095ccea9b,562fc2f2c2863ab7e79a9e4388a58a14,2018-08-07T04:24:17.000Z,29.99,22.93,1.0,boleto,1.0,52.92,45e290c98f407e6c90a75d81fc14d005,5.0,Segunda compra que faço!,"A capa aderiu bem no meu Redmi 4x, recomendo!",2018-08-15T00:00:00.000Z,2018-08-16T09:33:57.000Z,telefonia,57.0,364.0,1.0,150.0,22.0,7.0,14.0,telephony,cfa69922f9968e0e6271647abda09b09,64063,teresina,PI,-17.0,On Time
c04ccf5367e419a74f5589f156a0b8e1,6f7d7ececcfee77e1c4d624c81a37aa2,delivered,2017-09-30T19:45:40.000Z,2017-09-30T20:14:23.000Z,2017-10-03T17:06:05.000Z,2017-10-10T17:32:52.000Z,2017-10-30T00:00:00.000Z,1.0,6a1a04054158fe995e1688d8f79605b2,9616352088dcf83a7c06637f4ebf1c80,2017-10-09T20:14:23.000Z,59.9,13.44,1.0,credit_card,1.0,73.34,644537a36bc46b09f52e494d2922819a,5.0,null,null,2017-10-11T00:00:00.000Z,2017-10-11T22:24:22.000Z,esporte_lazer,59.0,254.0,1.0,1650.0,40.0,45.0,25.0,sports_leisure,2362ea945dafafd2f3c196effdbdb83e,11453,guaruja,SP,-20.0,On Time
cd38154bf340cc6b376898bd4b82b125,6c0f0dd8985cc0a789fb68327a00bc39,delivered,2018-05-07T15:06:12.000Z,2018-05-07T16:55:52.000Z,2018-05-09T15:48:00.000Z,2018-05-18T18:08:38.000Z,2018-05-28T00:00:00.000Z,1.0,53b36df67ebb7c41585e8d54d6772e08,7d13fca15225358621be4086e1eb0964,2018-05-11T16:55:52.000Z,99.9,0.0,1.0,credit_card,4.0,99.9,1576c7acebbaa1cf62b399bc62130148,5.0,null,null,2018-05-19T00:00:00.000Z,2018-05-21T03:18:06.000Z,relogios_presentes,33.0,523.0,3.0,584.0,16.0,11.0,13.0,watches_gifts,7c8cdb09963770391622f23f120085f7,24436,sao goncalo,RJ,-10.0,On Time
bbf778080cc883a8de2e500c0e490c75,437c6e906ba1e09eacb6d28d1de3f061,delivered,2018-04-01T21:03:55.000Z,2018-04-01T21:15:10.000Z,2018-04-02T19:33:05.000Z,2018-04-10T22:58:42.000Z,2018-05-08T00:00:00.000Z,1.0,873d2aa3911060e77ac89009410aa908,6c177e38df6d3f34182b1f1d427231bf,2018-04-10T21:15:10.000Z,148.0,22.75,1.0,credit_card,2.0,170.75,decd1f3ad4afa22a0544c99eb839a305,3.0,null,null,2018-04-11T00:00:00.000Z,2018-04-13T00:44:18.000Z,telefonia,54.0,172.0,2.0,150.0,20.0,5.0,12.0,telephony,09e9dc48aef9cb76de884bbbb8adf731,28895,rio das ostras,RJ,-28.0,On Time
bf79e4fa55a389d494f47feb2654892c,e8759aed1027f77226dddeb7c7481f11,delivered,2017-01-31T21:11:10.000Z,2017-02-01T09:45:26.000Z,2017-02-01T14:29:06.000Z,2017-03-13T12:09:45.000Z,2017-02-27T00:00:00.000Z,1.0,fe09eb5f7bfcb79d05df7c4e83ec204e,2a1348e9addc1af5aaa619b1a3679d6b,2017-02-04T21:11:10.000Z,14.9,14.52,1.0,boleto,1.0,29.42,6b63898cfd07a3793858c7591753983e,1.0,null,null,2017-03-01T00:00:00.000Z,2017-03-01T03:18:30.000Z,consoles_games,60.0,574.0,1.0,200.0,16.0,2.0,11.0,consoles_games,62972384465273ec1b0d3cf772abc390,29170,serra,ES,14.0,Delayed
fb7aedc5796ee214a87461ece45355e7,40d3460ad3b63de04990975d2fb3330c,delivered,2018-02-15T21:39:10.000Z,2018-02-16T07:50:27.000Z,2018-02-19T14:08:52.000Z,2018-03-05T19:59:37.000Z,2018-03-09T00:00:00.000Z,1.0,0f56d67a1f266a9cf5af6ffd7895bed6,5cf13accae3222c70a9cac40818ae839,2018-02-22T06:50:27.000Z,94.9,16.42,1.0,boleto,1.0,111.32,3fcb53d0f956c80ac7712fad7dc52529,5.0,null,null,2018-03-06T00:00:00.000Z,2018-03-07T12:08:07.000Z,pet_shop,53.0,1024.0,2.0,600.0,21.0,18.0,20.0,pet_shop,2872114274bbdff3c561c28366c1979b,4475,sao paulo,SP,-4.0,On Time
c6c304f8417f11d277f34b8a6ffe1532,3be9371fc3606f9f4572254708def45a,delivered,2018-04-30T09:10:16.000Z,2018-04-30T09:35:45.000Z,2018-05-03T06:31:00.000Z,2018-05-11T16:42:34.000Z,2018-05-25T00:00:00.000Z,1.0,2948658cb6abc82847412be7201bfc4c,955fee9216a65b617aa5c0531780ce60,2018-05-07T09:30:26.000Z,110.0,34.76,1.0,credit_card,3.0,144.76,d17f993c9535eb6fcef6095f4788aa16,3.0,null,null,2018-05-12T00:00:00.000Z,2018-05-13T00:40:17.000Z,beleza_saude,59.0,1030.0,5.0,3500.0,36.0,25.0,21.0,health_beauty,593e30b76f4138d5a9f0736ccedb9a40,58030,joao pessoa,PB,-14.0,On Time
90a35d9f1707a645c3bd2dda9c3f2643,5d94eb3a651e44419266ec8fddbd57be,delivered,2017-12-02T16:44:06.000Z,2017-12-02T16:59:01.000Z,2017-12-04T18:04:30.000Z,2017-12-19T16:44:45.000Z,2018-01-02T00:00:00.000Z,1.0,d2085f7e0f9533605386960fc7e987ec,aac29b1b99776be73c3049939652091d,2017-12-08T16:59:01.000Z,12.49,15.1,1.0,credit_card,1.0,110.36,null,null,null,null,null,null,ferramentas_jardim,40.0,207.0,4.0,150.0,16.0,2.0,11.0,garden_tools,a611c80155435e6a86012d159d9e5007,71741,brasilia,DF,-14.0,On Time
90a35d9f1707a645c3bd2dda9c3f2643,5d94eb3a651e44419266ec8fddbd57be,delivered,2017-12-02T16:44:06.000Z,2017-12-02T16:59:01.000Z,2017-12-04T18:04:30.000Z,2017-12-19T16:44:45.000Z,2018-01-02T00:00:00.000Z,2.0,d2085f7e0f9533605386960fc7e987ec,aac29b1b99776be73c3049939652091d,2017-12-08T16:59:01.000Z,12.49,15.1,1.0,credit_card,1.0,110.36,null,null,null,null,null,null,ferramentas_jardim,40.0,207.0,4.0,150.0,16.0,2.0,11.0,garden_tools,a611c80155435e6a86012d159d9e5007,71741,brasilia,DF,-14.0,On Time
90a35d9f1707a645c3bd2dda9c3f2643,5d94eb3a651e44419266ec8fddbd57be,delivered,2017-12-02T16:44:06.000Z,2017-12-02T16:59:01.000Z,2017-12-04T18:04:30.000Z,2017-12-19T16:44:45.000Z,2018-01-02T00:00:00.000Z,3.0,d2085f7e0f9533605386960fc7e987ec,aac29b1b99776be73c3049939652091d,2017-12-08T16:59:01.000Z,12.49,15.1,1.0,credit_card,1.0,110.36,null,null,null,null,null,null,ferramentas_jardim,40.0,207.0,4.0,150.0,16.0,2.0,11.0,garden_tools,a611c80155435e6a86012d159d9e5007,71741,brasilia,DF,-14.0,On Time
90a35d9f1707a645c3bd2dda9c3f2643,5d94eb3a651e44419266ec8fddbd57be,delivered,2017-12-02T16:44:06.000Z,2017-12-02T16:59:01.000Z,2017-12-04T18:04:30.000Z,2017-12-19T16:44:45.000Z,2018-01-02T00:00:00.000Z,4.0,d2085f7e0f9533605386960fc7e987ec,aac29b1b99776be73c3049939652091d,2017-12-08T16:59:01.000Z,12.49,15.1,1.0,credit_card,1.0,110.36,null,null,null,null,null,null,ferramentas_jardim,40.0,207.0,4.0,150.0,16.0,2.0,11.0,garden_tools,a611c80155435e6a86012d159d9e5007,71741,brasilia,DF,-14.0,On Time
fbfba2ffdcf0d5f4e4eeebc83a18b0d3,7decbed5e9dba1c414ec29e6642fc782,delivered,2018-03-18T16:14:17.000Z,2018-03-18T16:30:26.000Z,2018-03-20T15:09:35.000Z,2018-03-23T21:07:04.000Z,2018-04-10T00:00:00.000Z,1.0,7814c273ab16783d73a9863ebfa8b141,1025f0e2d44d7041d6cf58b6550e0bfa,2018-03-27T16:30:26.000Z,250.0,37.77,1.0,credit_card,4.0,287.77,dc3ae541bd971d5d47b552d5892c1c55,5.0,null,Otimo...,2018-03-24T00:00:00.000Z,2018-03-25T01:03:08.000Z,moveis_decoracao,51.0,756.0,1.0,12250.0,45.0,35.0,45.0,furniture_decor,6dfd32ebdda748f99584cb407510bb89,14500,ituverava,SP,-18.0,On Time
3b762d0fc1d3436171716bc6c3ae8497,37566e2c7b3fc323c530b838b0178401,delivered,2018-03-07T16:36:33.000Z,2018-03-08T12:45:28.000Z,2018-03-08T23:10:37.000Z,2018-04-02T17:12:33.000Z,2018-04-04T00:00:00.000Z,1.0,e91bea61ea0d665e4c445d6461586e13,4e5725ba188db8252977a4f0227bd462,2018-03-14T12:45:28.000Z,360.0,20.4,1.0,credit_card,3.0,380.4,7fda2e9bb9cbc1e7b6444e299d221934,5.0,null,null,2018-04-03T00:00:00.000Z,2018-04-03T19:12:07.000Z,informatica_acessorios,60.0,540.0,1.0,3400.0,21.0,17.0,15.0,computers_accessories,452185d4297d39dc139799ce818d8307,97065,santa maria,RS,-2.0,On Time
fc8b5696b23d0710ae737ff9c16f80ea,8953cac02ef5531e3b49afc55cc21232,delivered,2018-01-15T21:54:38.000Z,2018-01-15T22:10:41.000Z,2018-01-16T22:25:09.000Z,2018-01-27T12:09:29.000Z,2018-02-14T00:00:00.000Z,1.0,5389dbdf62ed8bee6b52fab9c9891f2e,897060da8b9a21f655304d50fd935913,2018-01-23T22:10:41.000Z,83.23,15.33,1.0,credit_card,1.0,98.56,70e766e69c12f5e68cacfcd5a367a6e6,3.0,null,bom produto.,2018-01-28T00:00:00.000Z,2018-01-29T21:14:37.000Z,informatica_acessorios,54.0,1416.0,3.0,200.0,16.0,14.0,13.0,computers_accessories,6b016ce767bbafe912ab0b8dce8e245b,88095,florianopolis,SC,-18.0,On Time
6debbd8568d730f4959d1fac74ed0315,66f7666afc694d88befe0d5e48871138,delivered,2018-01-12T19:23:58.000Z,2018-01-12T19:31:26.000Z,2018-01-23T00:08:27.000Z,2018-02-27T00:35:57.000Z,2018-02-14T00:00:00.000Z,1.0,5e211f15646acded537a9d1646f6a268,9c068d10aca38e85c50202e17b4a7e88,2018-01-18T19:31:26.000Z,194.9,39.26,1.0,credit_card,4.0,234.16,null,null,null,null,null,null,automotivo,59.0,759.0,2.0,2250.0,16.0,15.0,16.0,auto,b36e99aa28fa8a66d98742c741d653e9,40283,salvador,BA,13.0,Delayed
47cf7e28d8f434cd6a3f4825953cdbac,8fceafecb6f78c92c97dde2f6d1cac63,delivered,2018-05-03T20:57:34.000Z,2018-05-03T21:11:30.000Z,2018-05-04T10:42:00.000Z,2018-05-11T20:47:31.000Z,2018-05-17T00:00:00.000Z,1.0,b2f15c23f560da3b247e1090d9d12be7,2ff97219cb8622eaf3cd89b7d9c09824,2018-05-09T21:11:30.000Z,16.9,7.71,1.0,credit_card,1.0,49.22,fe1aad5c0dd87fd4e66e008a98b77ad2,5.0,Gostei.,Foi entrgue bem antes do prazo.,2018-05-12T00:00:00.000Z,2018-05-13T08:50:01.000Z,utilidades_domesticas,60.0,608.0,4.0,200.0,16.0,6.0,12.0,housewares,39c13cde8e30f2f4516cdcd3c3100ddf,11725,praia grande,SP,-6.0,On Time
47cf7e28d8f434cd6a3f4825953cdbac,8fceafecb6f78c92c97dde2f6d1cac63,delivered,2018-05-03T20:57:34.000Z,2018-05-03T21:11:30.000Z,2018-05-04T10:42:00.000Z,2018-05-11T20:47:31.000Z,2018-05-17T00:00:00.000Z,2.0,b2f15c23f560da3b247e1090d9d12be7,2ff97219cb8622eaf3cd89b7d9c09824,2018-05-09T21:11:30.000Z,16.9,7.71,1.0,credit_card,1.0,49.22,fe1aad5c0dd87fd4e66e008a98b77ad2,5.0,Gostei.,Foi entrgue bem antes do prazo.,2018-05-12T00:00:00.000Z,2018-05-13T08:50:01.000Z,utilidades_domesticas,60.0,608.0,4.0,200.0,16.0,6.0,12.0,housewares,39c13cde8e30f2f4516cdcd3c3100ddf,11725,praia grande,SP,-6.0,On Time
642b39405abba96bc0e134680e8ceb02,bffd28b4af20bc7b1a477fe80e190c77,unavailable,2017-03-05T09:28:24.000Z,2017-03-07T04:10:29.000Z,null,null,2017-04-03T00:00:00.000Z,null,null,null,null,null,null,1.0,boleto,1.0,214.1,c5a4690da16a9a92b4e419dba2f69daa,1.0,null,Perderam um cliente,2017-04-06T00:00:00.000Z,2017-04-06T14:43:10.000Z,null,null,null,null,null,null,null,null,null,20763743ec53eec3a9949781bf459e6e,88390,barra velha,SC,null,On Time
9f7d6c40a518954cc676b40cf3e2c61a,cb4f601a5eebf94e41b2bfc80cbc8e62,delivered,2018-05-01T19:11:36.000Z,2018-05-01T19:33:39.000Z,2018-05-07T12:31:00.000Z,2018-05-11T23:06:29.000Z,2018-05-29T00:00:00.000Z,1.0,0a57f7d2c983bcf8188589a5fea4a8da,4869f7a5dfa277a7dca6462dcf3b52b2,2018-05-09T19:31:19.000Z,95.9,17.58,1.0,credit_card,5.0,113.48,d0f64e0ac622b5a34c2c40479fbb2714,5.0,null,null,2018-05-12T00:00:00.000Z,2018-05-14T04:37:04.000Z,relogios_presentes,33.0,932.0,1.0,396.0,18.0,11.0,14.0,watches_gifts,a36022b1b85179867ad8ddec7393824e,1313,sao paulo,SP,-18.0,On Time
f4b84983666d1ac021c0522f00a405c0,6a4d0a6c3f1bbcd88b4e58633a4f8184,delivered,2018-08-21T12:21:04.000Z,2018-08-21T12:30:47.000Z,2018-08-21T14:56:00.000Z,2018-08-24T19:41:45.000Z,2018-08-24T00:00:00.000Z,1.0,8acf0061d1c7b72c3a4857db994ecc79,17ca9b9e9b9ef8fdb529001b49ebb50f,2018-08-23T12:30:47.000Z,69.97,11.98,1.0,credit_card,2.0,81.95,22c417c4ea6e742c0208dfea13e089a3,1.0,bom,"O produto não é o que eu esperava, mas serve",2018-08-25T00:00:00.000Z,2018-08-28T10:58:22.000Z,cama_mesa_banho,54.0,1004.0,1.0,1150.0,16.0,30.0,40.0,bed_bath_table,0afbb1db4938251436ec902d3e3b4c91,32183,contagem,MG,0.0,On Time
12988705c14f4a1b899dcfba47f4fd49,0a42f79acdee1c80dc33cc9539e13b9a,delivered,2018-05-11T01:03:08.000Z,2018-05-12T01:16:37.000Z,2018-05-15T14:20:00.000Z,2018-05-22T20:27:36.000Z,2018-06-06T00:00:00.000Z,1.0,3ac29f1f25166dcc60b97e65d9a5885c,440dd6ab244315c632130ecfb63827b1,2018-05-17T01:16:37.000Z,144.0,43.59,1.0,credit_card,2.0,187.59,5916eb7c953c3b7d03b45f14802cb708,5.0,10,Muito obrigado,2018-05-23T00:00:00.000Z,2018-05-26T02:47:31.000Z,esporte_lazer,60.0,1493.0,2.0,1050.0,80.0,8.0,15.0,sports_leisure,fa9d48426871b8a665348bae305bbc2a,86975,mandaguari,PR,-15.0,On Time
ab960bedab25b686fc5202ccf9be3094,588a6c2298f57752c9458dd79c675f36,delivered,2018-05-08T13:12:21.000Z,2018-05-08T13:35:16.000Z,2018-05-08T15:41:00.000Z,2018-05-14T22:05:43.000Z,2018-06-04T00:00:00.000Z,1.0,93a12c289ca2b78e7069e469f5053ef2,88460e8ebdecbfecb5f9601833981930,2018-05-22T13:30:59.000Z,144.9,14.13,1.0,credit_card,1.0,159.03,c8d86e9469cc55281daf9bb4a3f17507,1.0,"Pus 1, mas é zero estrela",Venda de cartuchos falsificados/usados (mensagem da minha impressora HP quando tentei instalar os cartuchos). Providências somente sob pressão. Enorme perda de tempo com todo o processo.,2018-05-15T00:00:00.000Z,2018-06-12T13:10:24.000Z,informatica_acessorios,55.0,408.0,1.0,233.0,16.0,14.0,15.0,computers_accessories,b0bc6af493883ddf6e65a498f4f197d3,80035,curitiba,PR,-21.0,On Time
44c20b916ad4112aab925e7ecbd6b1fe,36ba612573e878b95e3e5de1b17ee495,delivered,2018-04-12T17:12:52.000Z,2018-04-12T17:29:31.000Z,2018-04-13T19:05:02.000Z,2018-04-14T17:42:13.000Z,2018-04-30T00:00:00.000Z,1.0,d25142f887810041ec819fbabafa8c76,f262cbc1c910c83959f849465454ddd3,2018-04-18T17:29:31.000Z,99.99,7.56,1.0,credit_card,1.0,107.55,f054f9604fad625d8eb73a972592f911,5.0,null,null,2018-04-15T00:00:00.000Z,2018-04-16T21:58:48.000Z,informatica_acessorios,43.0,382.0,1.0,350.0,21.0,9.0,17.0,computers_accessories,6923959f3749c4dadeee7ef220231bfc,7793,cajamar,SP,-16.0,On Time
84270b9b2f185170b4b29b448ef3a0cc,b1fb921da8da31f114b8f25530967fe7,delivered,2017-06-19T20:32:27.000Z,2017-06-20T11:05:29.000Z,2017-06-21T09:58:41.000Z,2017-06-28T15:32:55.000Z,2017-07-07T00:00:00.000Z,1.0,777d2e438a1b645f3aec9bd57e92672c,4a3ca9315b744ce9f8e9374361493884,2017-06-26T11:05:29.000Z,69.9,12.83,1.0,boleto,1.0,82.73,be049948791daaa7ada6a0756ae8e9a2,4.0,null,Bom,2017-06-29T00:00:00.000Z,2017-06-30T01:02:31.000Z,cama_mesa_banho,58.0,689.0,1.0,950.0,45.0,15.0,35.0,bed_bath_table,e67af1efd445becc5019902668fe3218,16901,andradina,SP,-9.0,On Time
dd3f89a5330b29871785935cab37fcbc,bb2b8b9b95fc43819ab3ba6c5b6e3fd2,delivered,2018-02-05T11:07:13.000Z,2018-02-05T11:35:35.000Z,2018-02-09T17:52:06.000Z,2018-02-15T23:37:01.000Z,2018-02-23T00:00:00.000Z,1.0,7855801875dac05bda454284be8be7db,f76a3b1349b6df1ee875d1f3fa4340f0,2018-02-13T11:35:35.000Z,139.9,13.53,1.0,credit_card,1.0,153.43,67e1883c325520b179e45f978ad5aab5,5.0,null,null,2018-02-16T00:00:00.000Z,2018-02-19T10:48:36.000Z,utilidades_domesticas,58.0,1854.0,1.0,3500.0,36.0,30.0,32.0,housewares,af70fa34dfd5b02c0a4d7250a4026230,3111,sao paulo,SP,-8.0,On Time
26fa952896224ad19bba5529c49d077b,fb0eae96da2e5b5cd5b9756f883714cc,delivered,2018-06-21T21:44:11.000Z,2018-06-23T01:00:15.000Z,2018-06-25T08:27:00.000Z,2018-07-02T20:07:35.000Z,2018-07-20T00:00:00.000Z,1.0,d56c3ea4f42e37bc279359ab8ca16479,31561f325664a8a7aba4c8d0c3a9b3db,2018-06-28T01:00:15.000Z,39.49,15.38,1.0,credit_card,3.0,54.87,d08f77294705fac3818d969df4545826,5.0,Ótimo produto,Realmente é uma meia de qualidade.,2018-07-03T00:00:00.000Z,2018-07-03T23:31:48.000Z,automotivo,60.0,651.0,1.0,100.0,16.0,3.0,11.0,auto,7d9f821a5a0c0f80321140886696e7aa,90550,porto alegre,RS,-18.0,On Time

# Generate Executive KPIs

In [0]:
total_orders = df["order_id"].nunique()
gmv = df["payment_value"].sum()
aov = gmv / total_orders
avg_review = df["review_score"].mean()

print("Total Orders:", total_orders)
print("GMV:", round(gmv,2))
print("AOV:", round(aov,2))
print("Avg Review:", round(avg_review,2))

Total Orders: 99441
GMV: 20579664.01
AOV: 206.95
Avg Review: 4.02

# Analysis 1 — Delivery Delay vs Customer Satisfaction

In [0]:
df.groupby("delivery_status")["review_score"].mean()

delivery_status
Delayed    2.253393
On Time    4.132788
Name: review_score, dtype: float64

# Analysis 2 — Top Revenue Categories

In [0]:
category_perf = df.groupby(
    "product_category_name_english"
).agg({
    "payment_value":"sum",
    "review_score":"mean",
    "order_id":"nunique"
}).sort_values(
    by="payment_value",
    ascending=False
).head(10)

category_perf

                               payment_value  review_score  order_id
product_category_name_english
bed_bath_table                    1743998.80      3.890605      9417
health_beauty                     1662963.59      4.137026      8836
computers_accessories             1599481.06      3.936089      6689
furniture_decor                   1443963.61      3.912158      6449
watches_gifts                     1430553.48      4.017692      5624
sports_leisure                    1400223.07      4.107470      7720
housewares                        1097900.09      4.060428      5884
auto                               855095.68      4.064279      3897
garden_tools                       840721.59      4.023914      3518
cool_stuff                         781933.97      4.140767      3632

# Analysis 3 — Repeat Customer Analysis

In [0]:
customer_orders = df.groupby(
    "customer_unique_id"
)["order_id"].nunique().reset_index()

customer_orders.columns = [
    "customer_unique_id",
    "order_count"
]

In [0]:
repeat_rate = (
    customer_orders["order_count"] > 1
).mean()

print("Repeat Purchase Rate:", round(repeat_rate*100,2), "%")

Repeat Purchase Rate: 3.12 %